function sareToSinaWb(){var a=encodeURI(document.title);void function(a,d,c,f,g,e,l,m,n){function h(){window.open(["http://v.t.sina.com.cn/share/share.php?appkey=962772401",e].join(""),"mb",["toolbar=0,status=0,resizable=1,width=600,height=500,left=",(a.width-600)/2,",top=",(a.height-600)/2].join(""))||(k.href=["http://v.t.sina.com.cn/share/share.php?appkey=962772401",e].join(""))}var k=m||d.location;e=["&url=",c(k),"& title=",c(l||d.title),"&source=",c(f),"&sourceUrl=",c(g),"& content=",n||"gb2312",
"&pic=",c(e||"")].join("");/Firefox/.test(navigator.userAgent)?setTimeout(h,0):h()}(screen,document,encodeURIComponent,"","",a,"","","utf-8");return!1}
function sareToQqZoneAndIncludePyw(){var a=location.href;getSareContent();window.open("http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url="+a+"&"+(new Date).getTime(),"newwindow","height=500, width=580, top="+(screen.height-280)/2+", left="+(screen.width-550)/2+", toolbar=no, menubar=no, scrollbars=no, resizable=yes, location=no, status=no");return!1}
function sareToQqWb(){var a=encodeURI(document.title),b=encodeURI(document.location),d=encodeURI("");getSareContent();var c=encodeURI("appkey");window.open("http://v.t.qq.com/share/share.php?title="+a+"&url="+b+"&appkey="+c+"&site=&pic="+d,"\u8f6c\u64ad\u5230\u817e\u8baf\u5fae\u535a","width=700, height=680, top=0, left=0, toolbar=no, menubar=no, scrollbars=no, location=yes, resizable=yes, status=no");return!1}
function sareTo163Wb(){var a=location.href,b=document.title,d=getSareContent(),a="link = http://news.163.com &source="+encodeURIComponent(d)+"&info="+encodeURIComponent(b)+" "+encodeURIComponent(a);window.open("http://t.163.com/article/user/checkLogin.do?"+a+"&"+(new Date).getTime(),"newwindow","height=480, width=550, top="+(screen.height-280)/2+", left="+(screen.width-550)/2+", toolbar=no, menubar=no, scrollbars=no, resizable=yes, location=no, status=no");return!1}
function sareToRenRen(){var a=location.href;getSareContent();void function(b,d,c){function f(){window.open(["http://share.renren.com/share/buttonshare?link=",e].join(""),"xnshare",["toolbar=0,status=0,resizable=1,width=626,height=436,left=",(b.width-626)/2,",top=",(b.height-436)/2].join(""))||(g.href=["http://share.renren.com/share/buttonshare?link=",e].join(""))}var g=a,e=[c(g),"&title=",c("")].join("");/Firefox/.test(navigator.userAgent)?setTimeout(f,0):f()}(screen,document,encodeURIComponent);
return!1}function sareToKaiXin(){var a=location.href,b=getSareContent(),a="http://www.kaixin001.com/repaste/share.php?rtitle=&rurl="+encodeURIComponent(a)+"&rcontent="+b+"";window.open(a+"&"+(new Date).getTime(),"newwindow","height=500, width=580, top="+(screen.height-280)/2+", left="+(screen.width-550)/2+", toolbar=no, menubar=no, scrollbars=no, resizable=yes, location=no, status=no");return!1}
function shareToBaiDuKj(){var a=location.href,b=document.title,d=getSareContent(),a="http://apps.hi.baidu.com/share/?url="+encodeURIComponent(a)+"&iu="+encodeURIComponent(b)+"&dc="+encodeURIComponent(d)+"&fr=ien#nw=1";window.open(a+"&"+(new Date).getTime(),"newwindow","height=700, width=626, top="+(screen.height-280)/2+", left="+(screen.width-550)/2+", toolbar=no, menubar=no, scrollbars=no, resizable=yes, location=no, status=no");return!1}
function getSareContent(){return'<a href="'+document.location+'" title="" target="_blank">'+document.title+"</a>"};
