String.prototype.replaceAll=function(a,b){var c=new RegExp(a.replace(/([\(\)\[\]\{\}\^\$\+\-\*\?\.\"\'\|\/\\])/g,"\\$1"),"ig");return this.replace(c,b)};String.prototype.startWith=function(a){return(new RegExp("^"+a)).test(this)};String.prototype.endWith=function(a){return(new RegExp(a+"$")).test(this)};Array.prototype.contains=function(a){for(var b=this.length;b--;)if(this[b]===a)return!0;return!1};
function alertPauseJsGn(){alertMessageBox("\u5bf9\u4e0d\u8d77\u8be5\u529f\u80fd\u6682\u672a\u5f00\u653e!")}function alertDisabledJsGn(){alertMessageBox("\u5bf9\u4e0d\u8d77\u8be5\u529f\u80fd\u5df2\u7981\u7528")}function isJsPause(){alertPauseJsGn();return!0}function pauseJsGn(){alertPauseJsGn();return!1}function isBlank(a){return void 0!=a&&a&&""!=$.trim(a)?!1:!0}function isConfirmSc(){return confirm("\u786e\u5b9a\u5220\u9664?")?!0:!1}
function isConfirmPlsc(){return confirm("\u786e\u5b9a\u6279\u91cf\u5220\u9664?")?!0:!1}function isConfirmPlcrjt(){return confirm("\u786e\u5b9a\u6279\u91cf\u751f\u6210\u9759\u6001?")?!0:!1}function isConfirmPlscjt(){return confirm("\u786e\u5b9a\u6279\u91cf\u5220\u9664\u9759\u6001?")?!0:!1}function isKjExsit(a){return 0==$("#"+a).length?!1:!0}function isKjHasText(a){return""!=$.trim($("#"+a).text())?!0:!1}
function isKjExsitIfNotDoAlert(a){return isKjExsit(a)?!0:(alertMessageBox(a+"\u63a7\u4ef6\u4e0d\u5b58\u5728"),!1)}function isKjHasTextAndAlert(a){return isKjHasText(a)?(alertMessageBox(text),!0):!1}function getSafeFloat(a){return isNaN(parseFloat(a))?0:a}function getActionByHz(a){var b=$("#path").val();return getLinkPath(b,a)}function getActionAppendCs(a,b){var c="?";-1!=a.indexOf(c)&&(c="&");return getActionByHz(a)+c+b}
function getResPathByHz(a){var b=$("#resPath").val();return getLinkPath(b,a)}function getLinkPath(a,b){a=$.trim(a);b=$.trim(b);return b.startWith("http")?b:a+"/"+subFirst(b,"/")}
function getTime(){var a=new Date,b=a.getHours(),c=a.getMinutes(),d=a.getSeconds();2>b.toString().length&&(b="0"+b);2>c.toString().length&&(c="0"+c);2>d.toString().length&&(d="0"+d);return a.getFullYear()+"\u5e74"+(a.getMonth()+1)+"\u6708"+a.getDate()+"\u65e5  "+b+":"+c+":"+d+"  "+"\u661f\u671f\u5929 \u661f\u671f\u4e00 \u661f\u671f\u4e8c \u661f\u671f\u4e09 \u661f\u671f\u56db \u661f\u671f\u4e94 \u661f\u671f\u516d".split(" ")[a.getDay()]+"  "}
function getPageScroll(){var a,b;window.pageYOffset?(b=window.pageYOffset,a=window.pageXOffset):document.documentElement&&document.documentElement.scrollTop?(b=document.documentElement.scrollTop,a=document.documentElement.scrollLeft):document.body&&(b=document.body.scrollTop,a=document.body.scrollLeft);return{L:a,T:b}}function getHiddenValue(a){return $("#[id='"+a+"']:hidden").val()}function getVisibleValue(a){return $("#[id='"+a+"']:visible").val()}
function getHiddenObj(a){return $("#[id='"+a+"']:hidden")}function getVisibleObj(a){return $("#[id='"+a+"']:visible")}function getObjsById(a){return $("#[id='"+a+"']")}function subFirst(a,b){a.startWith(b)&&(a=a.substring(a.indexOf(b)+b.length,a.length));return a}function subLast(a,b){-1!=a.endWith(b)&&(a=a.substring(0,a.lastIndexOf(b)));return a}
function bindShowAndHideDivByThumbAndContent(a,b,c,d){$("#"+a).bind("click",function(e){$("#"+b).is(":visible")?hideAndSetBackGroundPosition(a,b,d):fadeInAndSetBackGroundPosition(a,b,c)})}function hideAndSetBackGroundPosition(a,b,c){$("#"+b).hide();$("#"+a).css("background-position",c)}function fadeInAndSetBackGroundPosition(a,b,c){$("#"+b).fadeIn();$("#"+a).css("background-position",c)}function getStrCxCs(a,b){var c=a.length,d=b.length;return 0<d&&c>d?(c-a.replaceAll(b,"").length)/d:0}
function subStrByTimes(a,b,c){for(var d=0;d<c;d++)a=a.substring(a.indexOf(b)+1,a.length);return a}function subStrByTimesToAddTargetAndSubStr(a,b,c){for(var d=0;d<c;d++)a=a.substring(a.indexOf(b)+1,a.length);return b+a}function compareHzd(a,b){return b>a?!0:!1}function selectFocus(a){""!=a&&($("#"+a).select(),$("#"+a).focus())}function startOpenUrl(a){a=getLinkPath($("#path").val(),a);window.open(a)}function startLocationHref(a){location.href=a;return!1}
function startSubmit(a){$("#"+a).submit();return!1}function startSubmitBySetAction(a,b){$("#"+a).attr("action",b);$("#"+a).submit();return!1}function prepareElementsForFormSubmitByDph(a,b,c){$("#[id='"+b+"']:hidden").remove();$("#[id='"+c+"']:visible").prependTo($("#"+a)).hide()}function isIe6(){return $.browser.msie&&"6.0"==$.browser.version?!0:!1}function isGuGe(){return-1!=navigator.userAgent.indexOf("Chrome")}function isHuoHu(){return-1!=navigator.userAgent.indexOf("Firefox")}
function isIeVersion(a){return $.browser.msie&&$.browser.version==a?!0:!1}function getRandomColor(){return"#"+("00000"+(16777215*Math.random()+.5>>0).toString(16)).slice(-6)}function getOrImgPath(a){if(!a||-1==a.indexOf("_")||-1==a.indexOf("."))return a;var b=a.substring(0,a.indexOf("_")),c=a.substring(a.indexOf("_")+1,a.length);a=a.substring(a.lastIndexOf("."),a.length);c=-1!=c.indexOf("_")?c.substring(0,c.indexOf("_")):c.substring(0,c.lastIndexOf("."));return b+"_"+c+a}
function getZdWiImgPath(a,b){if(!a||-1==a.indexOf("_")||-1==a.indexOf("."))return a;var c=!1;-1!=a.substring(a.indexOf("_")+1,a.length).indexOf("_")&&(c=!0);var d=a.substring(a.lastIndexOf("."),a.length),e="";c?(e=a.substring(0,a.indexOf("_")),c=a.substring(a.indexOf("_")+1,a.length),e=e+"_"+c.substring(0,c.indexOf("_"))):e=a.substring(0,a.lastIndexOf("."));return e+"_"+b+d}function textAutoGrow(a){$(a).autoGrowInput({maxWidth:300})}
function textAutoGrowWithMaxWidth(a,b){$("#"+a).autoGrowInput({maxWidth:b})}function textLimit(a,b,c){a.value.length>c?(alertMessageBox("\u5df2\u8fbe\u5230"+c+"\u4e2a\u5b57\u7b26\u8d85\u51fa\u7684\u5c06\u81ea\u52a8\u53bb\u9664!"),a.value=a.value.substring(0,c),a.focus()):$("#"+b).text(c-a.value.length)}function textAreaAutoGrow(a){$("textarea#"+a).autoResize({onResize:function(){$(this).css({opacity:1})},animateCallback:function(){$(this).css({opacity:1})},animateDuration:300,extraSpace:20})}
function textLimitKindEditor(a,b,c){var d=a.text();d.length>c&&(a.text(d.substring(0,c)),a.appendHtml(""));0>c-d.length?$("#"+b).html(main.m_wordLimit+"<strong>"+c+"!</strong>"):$("#"+b).text(c-d.length)}function clickCustomerCheckBox(a){$("#"+a).click();$("#"+a).trigger("updateState")}function checkbox_qx(a,b){var c=$("input[name='"+a+"']")[0];checkbox_select_all_cancel(b);c.checked?checkbox_select_all(b):checkbox_select_all_cancel(b);$("input[type=checkbox]").trigger("updateState")}
function checkbox_select_all(a){$("input[name='"+a+"']").each(function(){$(this).get(0).defaultChecked=!0;$(this).attr("checked",!0)})}function checkbox_select_all_cancel(a){$("input[name='"+a+"']").each(function(){$(this).get(0).defaultChecked=!1;$(this).attr("checked",!1)})}function checkbox_select_all_reverse(a){$("input[name='"+a+"']").each(function(){$(this).get(0).defaultChecked=!this.checked;$(this).attr("checked",!this.checked)})}
function divShowAndHideByJjh(a,b,c,d){0==$("#"+b).length?alertMessageBox("\u5bf9\u4e0d\u8d77,\u5143\u7d20:"+b+"\u4e0d\u5b58\u5728"):"none"==$("#"+b)[0].style.display?($("#"+b).fadeIn("fast"),$("#"+a)[0].src=d):($("#"+b).fadeOut("fast"),$("#"+a)[0].src=c)}function ajaxLoading(a,b){var c=$("#"+a).width()/2,d=$("#"+a).height()/2;$("#"+a).append("<img id='loadingImage' style='position:absolute;top:"+d+"px;left:"+c+"px;' src='"+b+"' />")}
function ajaxLoadingOver(a){$("#loadingImage",$("#"+a)).remove()}
function tableChangeColor(a,b,c,d,e){if(document.getElementById(a)){a=document.getElementById(a).getElementsByTagName("tr");for(var f=1;f<a.length;f++)a[f].style.backgroundColor=0==a[f].sectionRowIndex%2?b:c,a[f].onclick=function(){"1"!=this.x?(this.style.backgroundColor=e,this.x="1"):(this.style.backgroundColor=0==this.sectionRowIndex%2?b:c,this.x="0")},a[f].onmouseover=function(){"1"!=this.x&&(this.style.backgroundColor=d)},a[f].onmouseout=function(){"1"!=this.x&&(this.style.backgroundColor=0==
this.sectionRowIndex%2?b:c)}}}function tableChangeColor(a,b,c,d){if(document.getElementById(a)){a=document.getElementById(a).getElementsByTagName("tr");for(var e=1;e<a.length;e++)a[e].style.backgroundColor=0==a[e].sectionRowIndex%2?b:c,a[e].onmouseover=function(){"1"!=this.x&&(this.style.backgroundColor=d)},a[e].onmouseout=function(){"1"!=this.x&&(this.style.backgroundColor=0==this.sectionRowIndex%2?b:c)}}}
function tableToJqueryDataTable(a){$("#"+a).dataTable({bPaginate:!1,bInfo:!1,bFilter:!1,bSort:!0,colReorder:!0})}function setAddSubIds(a,b){$("#[id^='"+a+"']").each(function(c){var d=$(this).parentsUntil("tr").parent("tr").next();$(this).attr("id",a+(c+1));$(d).attr("id",b+(c+1))})}function formLoading(a,b,c){$("#"+a).submit(function(){var a=$("#"+b).width()/2,e=$("#"+b).height()/2;$("#"+b).append("<img id='loadingImage' style='position:absolute;top:"+e+"px;left:"+a+"px;' src='"+c+"' />")})}
function isSplitPageByMuti(){return"true"==$("#splitIsMuti").val()?!0:!1}function subOneByPageLevel(){if(isSplitPageByMuti()&&isKjExsitIfNotDoAlert("submitType")){$("#submitType").val("goBack");var a=1*$("#pageLevel").val();$("#[id='pageLevel']").val(a-1)}}function addOneByPageLevel(){if(isSplitPageByMuti()&&isKjExsitIfNotDoAlert("submitType")){$("#submitType").val("goFront");var a=1*$("#pageLevel").val();$("#[id='pageLevel']").val(a+1)}}
function openPage(a){$("#splitPageDqNum").val(a);setSplitValueAndSubmit()}function selectOpenPage(){$("#splitPageDqNum").val($("#splitPageSelect").val());setSplitValueAndSubmit()}function numberOpenPage(a){$("#splitPageDqNum").val(a);setSplitValueAndSubmit()}function selectOpenMyNumZdy(){$("#splitPageDqNum").val(1);$("#splitPageMyNumZdy").val($("#splitPageSelect2").val());setSplitValueAndSubmit()}
function setSplitValueAndSubmit(){if(isKjExsitIfNotDoAlert("submitType")){$("#submitType").val("\u70b9\u51fb\u5206\u9875");var a=$("#splitPageFormAction").val();if(""!=a&&"null"!=a){var b=$("#splitPageFormId").val();$("#"+b).attr("action",a)}$("#"+$("#splitPageFormId").val()).submit();return!1}};
