function fiNULL(a){return reg_NULL(a)?"":a=a.replace(/(^\s*)|(\s*$)/g,"")}function fiNULL2(a){return reg_NULL(a)?"":a=a.replace(/\s*/g,"")}function fiYw(a){return reg_NULL(a)?"":a=a.replace(/[a-zA-Z]/g,"")}function fiDxYw(a){return reg_NULL(a)?"":a=a.replace(/[A-Z]/g,"")}function fiChinese(a){return reg_NULL(a)?"":a=a.replace(/[\u4e00-\u9fa5]/g,"")}function fiSz(a){return reg_NULL(a)?"":a=a.replace(/[0-9]/g,"")}
function fiYwChinese(a){return reg_NULL(a)?"":a=a.replace(/[a-zA-Z\u4e00-\u9fa5]/g,"")}function fiTSZF(a){return reg_NULL(a)?"":a=a.replace(/[`~!@#$%^&*()+=|{}':;'\[\]<>\/?~\uff01@#\uffe5%\u2026\u2026&*\uff08\uff09\u2014\u2014+|{}\u3010\u3011\u2018\uff1b\uff1a\u201d\u201c\u2019\u3002\uff0c\u3001\uff1f]/g,"")}function fiDxW(a){return reg_NULL(a)?"":a=a.replace(/\W/g,"")}function ficChinese(a){return reg_NULL(a)?"":a=a.replace(/[^\u4e00-\u9fa5]+/g,"")}
function ficSz(a){return reg_NULL(a)?"":a=a.replace(/[^0-9]+/g,"")}function ficSz002(a){return reg_NULL(a)?"":a=a.replace(/[^1-9]+/g,"")}function ficYw(a){return reg_NULL(a)?"":a=a.replace(/[^a-zA-Z]+/g,"")}function reg_True(a){return!0}function reg_False(a){return!0}function reg_NULL(a){return void 0==a||""==a||0==a.length?!0:!1}function reg_AcNull(a){return/\s*\S+/.test(a)}function reg_AcDcNull(){for(var a=/\s*\S+/,b=0;b<arguments.length;b++)if(!a.test(arguments[b]))return!1;return!0}
function reg_Zf(a){return reg_NULL(a)?!0:/^.+$/.test(a)}function reg_Zf2(a){return reg_NULL(a)?!1:reg_Zf(a)}function reg_Zw(a){return reg_NULL(a)?!0:/^[\u4E00-\u9FA5]+$/.test(a)}function reg_Zw2(a){return reg_NULL(a)?!1:reg_Zw(a)}function reg_Sz(a){return reg_NULL(a)?!0:/^(-?\d+)(\.\d+)?$/.test(a)}function reg_Sz2(a){return reg_NULL(a)?!1:reg_Sz(a)}function reg_Zfds(a){return reg_NULL(a)?!0:/^[1-9]\d*\.\d*|0\.\d*[1-9]\d*$/.test(a)}function reg_Zfds2(a){return reg_NULL(a)?!1:reg_Zfds(a)}
function reg_Ffds(a){return reg_NULL(a)?!0:/^-([1-9]\d*\.\d*|0\.\d*[1-9]\d*)$/.test(a)}function reg_Ffds2(a){return reg_NULL(a)?!1:reg_Ffds(a)}function reg_Lzfds(a){return reg_NULL(a)?!0:/^[1-9]\d*\.\d*|0\.\d*[1-9]\d*|0?\.0+|0$/.test(a)}function reg_Lzfds2(a){return reg_NULL(a)?!1:reg_Lzfds(a)}function reg_Lffds(a){return reg_NULL(a)?!0:/^(-([1-9]\d*\.\d*|0\.\d*[1-9]\d*))|0?\.0+|0$/.test(a)}function reg_Lffds2(a){return reg_NULL(a)?!1:reg_Lffds(a)}
function reg_Zsz(a){return reg_NULL(a)?!0:/^[+]?\d+|\d+[.]?\d+$/.test(a)}function reg_Zsz2(a){return reg_NULL(a)?!1:reg_Zsz(a)}function reg_Fsz(a){return reg_NULL(a)?!0:/^[-]?\d+|\d+[.]?\d+$/.test(a)}function reg_Fsz2(a){return reg_NULL(a)?!1:reg_Fsz(a)}function reg_Zfsz(a){return reg_NULL(a)?!0:/^[+-]?\d+|[+-]\d+[.]?\d+$/.test(a)}function reg_Zfsz2(a){return reg_NULL(a)?!1:reg_Zfsz(a)}function reg_Zfszyxdh(a){return reg_NULL(a)?!0:/^[+-]?[.]?\\d+|[+-]?\\d+[.]?\\d+$/.test(a)}
function reg_Zfszyxdh2(a){return reg_NULL(a)?!1:reg_Zfszyxdh(a)}function reg_Zm(a){return reg_NULL(a)?!0:/^[a-zA-Z]*$/.test(a)}function reg_Zm2(a){return reg_NULL(a)?!1:reg_Zm(a)}function reg_ZwSz(a){return reg_NULL(a)?!0:/^[0-9\u4e00-\u9fa5]*$/.test(a)}function reg_ZwSz2(a){return reg_NULL(a)?!1:reg_ZwSz(a)}function reg_ZwZm(a){return reg_NULL(a)?!0:/^[A-Za-z\u4e00-\u9fa5]*$/.test(a)}function reg_ZwZm2(a){return reg_NULL(a)?!1:reg_ZwZm(a)}
function reg_SzZm(a){return reg_NULL(a)?!0:/^[0-9A-Za-z]*$/.test(a)}function reg_SzZm2(a){return reg_NULL(a)?!1:reg_SzZm(a)}function reg_ZwSzZm(a){return reg_NULL(a)?!0:/^[A-Za-z0-9\u4e00-\u9fa5]*$/.test(a)}function reg_ZwSzZm2(a){return reg_NULL(a)?!1:reg_ZwSzZm(a)}function reg_ZwSzXHX(a){return reg_NULL(a)?!0:/^[0-9\u4e00-\u9fa5_]*$/.test(a)}function reg_ZwSzXHX2(a){return reg_NULL(a)?!1:reg_ZwSzXHX(a)}function reg_ZwZmXHX(a){return reg_NULL(a)?!0:/^[A-Za-z\u4e00-\u9fa5_]*$/.test(a)}
function reg_ZwZmXHX2(a){return reg_NULL(a)?!1:reg_ZwZmXHX(a)}function reg_SzZmXHX(a){return reg_NULL(a)?!0:/^[0-9A-Za-z_]*$/.test(a)}function reg_SzZmXHX2(a){return reg_NULL(a)?!1:reg_SzZmXHX(a)}function reg_ZwSzZmXHX(a){return reg_NULL(a)?!0:/^[\w\u4e00-\u9fa5]+$/.test(a)}function reg_ZwSzZmXHX2(a){return reg_NULL(a)?!1:reg_ZwSzZmXHX(a)}function reg_ZwSzZmKhJh(a){return reg_NULL(a)?!0:/^[A-Za-z0-9\u4e00-\u9fa5\(\)\-]*$/.test(a)}
function reg_ZwSzZmKhJh2(a){return reg_NULL(a)?!1:reg_ZwSzZmKhJh(a)}function reg_Zzs(a){return reg_NULL(a)?!0:/^[0-9]*[1-9][0-9]*$/.test(a)}function reg_Zzs2(a){return reg_NULL(a)?!1:reg_Zzs(a)}function reg_Lzzs(a){return reg_NULL(a)||"0"==a.replace(/(^\s*)|(\s*$)/g,"")?!0:/^[0-9]*[1-9][0-9]*$/.test(a)}function reg_Lzzs2(a){return reg_NULL(a)?!1:reg_Lzzs(a)}function reg_Fylzzs(a){if(reg_NULL(a))return!0;var b=a.replace(/(^\s*)|(\s*$)/g,"");return"-1"==b||"0"==b?!0:/^[0-9]*[1-9][0-9]*$/.test(a)}
function reg_Fylzzs2(a){return reg_NULL(a)?!1:reg_Fylzzs(a)}function reg_ZzsXs(a){return reg_NULL(a)?!0:/[0-9]+(.[0-9]+)?/.test(a)}function reg_ZzsXs2(a){return reg_NULL(a)?!1:reg_ZzsXs(a)}function reg_DhZfc(a){return reg_NULL(a)?!0:/^([A-Za-z0-9\u4e00-\u9fa5]+[,])*([A-Za-z0-9\u4e00-\u9fa5]+)$/.test(a)}function reg_DhZfc2(a){return reg_NULL(a)?!1:reg_DhZfc(a)}
function reg_DhZfcKhXhxHgDh(a){return reg_NULL(a)?!0:/^([A-Za-z0-9\u4e00-\u9fa5\(\)_\-\u3001]+[,])*([A-Za-z0-9\u4e00-\u9fa5\(\)_\-\u3001]+)$/.test(a)}function reg_DhZfcKhXhxHgDh2(a){return reg_NULL(a)?!1:reg_DhZfcKhXhxHgDh(a)}function reg_Qq(a){return reg_NULL(a)?!0:/^\d{5,10}$/.test(a)}function reg_Qq2(a){return reg_NULL(a)?!1:reg_Qq(a)}
function reg_Ip(a){return reg_NULL(a)?!0:/^\b((?!\d\d\d)\d+|1\d\d|2[0-4]\d|25[0-5])\.((?!\d\d\d)\d+|1\d\d|2[0-4]\d|25[0-5])\.((?!\d\d\d)\d+|1\d\d|2[0-4]\d|25[0-5])\.((?!\d\d\d)\d+|1\d\d|2[0-4]\d|25[0-5])\b$/.test(a)}function reg_Ip2(a){return reg_NULL(a)?!1:reg_Ip(a)}function reg_Email(a){return reg_NULL(a)?!0:/^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+((\.[a-zA-Z0-9_-]{2,3}){1,2})$/.test(a)}function reg_Email2(a){return reg_NULL(a)?!1:reg_Email(a)}
function reg_SFZ(a){return reg_NULL(a)?!0:/^\d{18}|\d{17}(X){1}$/.test(a)}function reg_SFZ2(a){return reg_NULL(a)?!1:reg_SFZ(a)}function reg_Yb(a){return reg_NULL(a)?!0:/^[0-9]{6}$/.test(a)}function reg_Yb2(a){return reg_NULL(a)?!1:reg_Yb(a)}function reg_Sj(a){return reg_NULL(a)?!0:/^1\d{10}$/.test(a)}function reg_Sj2(a){return reg_NULL(a)?!1:reg_Sj(a)}function reg_SjZj(a){return reg_NULL(a)?!0:/^1\d{10}$|^(\d{3,4}-)\d{7,8}(-\d{1,6})?$/.test(a)}
function reg_SjZj2(a){return reg_NULL(a)?!1:reg_SjZj(a)}function reg_ZheKou(a){return reg_NULL(a)?!0:/^([0][.][1-9][0-9]|[0][.][0-9][1-9])|[1][.][0][0]$/.test(a)}function reg_ZheKou2(a){return reg_NULL(a)?!1:reg_ZheKou(a)}function reg_MianZhi(a){return reg_NULL(a)?!0:/^([0-9]+[\u5143][,])*([0-9]+[\u5143])$/.test(a)}function reg_MianZhi2(a){return reg_NULL(a)?!1:reg_MianZhi(a)}function reg_UserName(a){return reg_NULL(a)||/^[0-9a-zA-Z_]{6,18}$/.test(a)&&!reg_Sz2(a.substring(0,1))?!0:!1}
function reg_UserName2(a){return reg_NULL(a)?!1:reg_UserName(a)}function reg_PetName(a){return reg_NULL(a)||/^[0-9a-zA-Z\u4e00-\u9fa5]{2,20}$/.test(a)&&!reg_Sz2(a.substring(0,1))?!0:!1}function reg_PetName2(a){return reg_NULL(a)?!1:reg_PetName(a)}function reg_Password(a){return reg_NULL(a)?!0:/^[0-9a-zA-Z_]{6,20}$/.test(a)}function reg_Password2(a){return reg_NULL(a)?!1:reg_Password(a)}function reg_Rq(a){return reg_NULL(a)?!0:/^\d{4}\-[01]?\d\-[0-3]?\d$|^[01]\d\/[0-3]\d\/\d{4}$/.test(a)}
function reg_Rq2(a){return reg_NULL(a)?!1:reg_Rq(a)}function reg_RqF(a){return reg_NULL(a)?!0:/^\d{4}\-[01]?\d\-[0-3]?\d$|^[01]\d\/[0-3]\d\/\d{4}$|^\d{4}\u5e74[01]?\d\u6708[0-3]?\d[\u65e5\u53f7]$/.test(a)}function reg_RqF2(a){return reg_NULL(a)?!1:reg_RqF(a)}function reg_RqT(a){return reg_NULL(a)?!0:/^\d{4}\-[01]?\d\-[0-3]?\d (\d{2}):(\d{2}):(\d{2})$|^[01]\d\/[0-3]\d\/\d{4} (\d{2}):(\d{2}):(\d{2})$/.test(a)}function reg_RqT2(a){return reg_NULL(a)?!1:reg_RqT(a)}
function reg_ActionJg(a){return reg_NULL(a)?!0:/^([0-9a-zA-Z])+(!){1}([0-9a-zA-Z])+(.action){1}$/.test(a)}function reg_ActionJg2(a){return reg_NULL(a)?!1:reg_ActionJg(a)}function reg_ImageType(a){return reg_NULL(a)?!0:/(.*\.(jpg|gif|png|jpeg|bmp|JPG|GIF|PNG|JPEG|BMP))/.test(a)}function reg_ImageType2(a){return reg_NULL(a)?!1:reg_ImageType(a)}function reg_ZmKt(a){return reg_NULL(a)?!0:/^[a-zA-Z]+\w*$/.test(a)}function reg_ZmKt2(a){return reg_NULL(a)?!1:reg_ZmKt(a)}
function reg_Yzm(a){return reg_NULL(a)?!0:/^[a-zA-Z0-9]{4,6}$/.test(a)}function reg_Yzm2(a){return reg_NULL(a)?!1:reg_Yzm(a)}function reg_SjYzm(a){return reg_NULL(a)?!0:/^\d{6}$/.test(a)}function reg_SjYzm2(a){return reg_NULL(a)?!1:reg_SjYzm(a)}function reg_OrderNumber(a){return reg_NULL(a)?!0:/^\d{10,30}$/.test(a)}function reg_OrderNumber2(a){return reg_NULL(a)?!1:reg_OrderNumber(a)}
function mReg_ZfCd(a,b,c){a=fiNULL(a);return reg_NULL(a)||(a.length>b||a.length==b)&&(a.length<c||a.length==c)?!0:!1}function mReg_ZfCd2(a,b,c){return reg_NULL(a)?!1:mReg_ZfCd(a,b,c)};
