function bindReset(a,b){$("#"+a).bind("click",function(a){a=b.split(",");for(var d=0;d<a.length;d++){var e=$.trim(a[d]);$("#"+e).val("")}})}
function bindArtZoom(a){$(a).each(function(){var a=$(this),c=new Image;c.src=$(a).attr("src");c.onload=function(){var c=$(a).width(),e=$(a).height(),f=100<c?100:c,g=0,h=0;c>e?(g=f,h=f*e/c):(g=f*c/e,h=f);$(a).width(f);g*=3;h*=3;a.artZoom({path:"/ex/jquery.form/jquery.artZoom/images",preload:!0,minWidth:100,maxWidth:g>c?c:g,minHeight:50,maxHeight:h>e?e:h,left:"\u5de6\u65cb\u8f6c",right:"\u53f3\u65cb\u8f6c",source:"\u770b\u539f\u56fe"})}})}
function bindClickImgYzm(a){$("#[id^='"+a+"']").bind("click",function(){var a=$(this),c=a.attr("src"),d=(new Date).valueOf();-1!=c.indexOf("?")&&(c=c.substring(0,c.indexOf("?")));a.attr("src",c+"?timestamp="+d)}).css("cursor","pointer")}function bindClickEnterSubmit(a){$(document).bind("keydown","return",function(b){"13"==b.keyCode&&$("#"+a).click()})}
function bindAnimateInputField(a,b,c){$("#"+a).focus(function(){$("#"+b).animate({opacity:"0"},"fast");$(this).val()==c&&""==$(this).val()}).blur(function(){""==$(this).val()&&($(this).val()==c,$("#"+b).animate({opacity:"0.7"},"fast"))});$("#"+b).animate({opacity:"0.7"},"fast");$("#"+b).bind("click",function(){$(this).remove();$("#"+a).focus()})}function bindAlertHiddenSpanText(a){isKjExsitIfNotDoAlert(a)&&isKjHasTextAndAlert(a)}
function bindClickTextAndSetTextAppendToValue(a,b){var c=!1;$("#[id^='"+a+"']").bind("click",function(){$("#"+b).val($.trim($("#"+b).val())+$.trim($(this).text()));c||($("#"+b).focus(),c=!0)})}function bindAutocomplete(a,b){bindAutocompleteWithWidth(a,b,198)}
function bindAutocompleteWithWidth(a,b,c){$("#"+a).attr("autocomplete","off");$("#"+a).css("color","#bcbcbc").focus(function(){$(this).val()==this.defaultValue&&$(this).css("color","#640000")});$("#"+a).blur(function(){""==$.trim($(this).val())?$(this).css("color","#bcbcbc"):$(this).css("color","#640000")});if(0==$("#searchType").length)alertMessageBox("\u81ea\u52a8\u5b8c\u6210\u529f\u80fd\u9875\u9762\u5fc5\u987b\u81f3\u5c11\u5305\u542b\u4e00\u4e2a\u641c\u7d22\u7c7b\u578b:searchType");else{var d=
"?";-1!=b.indexOf("?")&&(d="&");d=d+"searchType="+encodeURI($("#searchType").val());b+=d;$("#"+a).autocomplete(b,{max:50,width:c,delay:200,autoFill:!1,dataType:"json",matchSubset:!0,scrollHeight:200,matchContains:!0,parse:function(a){return $.map(a,function(a){return{data:a,value:a.name}})},formatItem:function(a,b,c){return a.name},formatMatch:function(a,b,c){return a.name},formatResult:function(a){return a.name}}).result(function(a,b,c){b.id&&$("#id").val(b.id);b.code&&$("#code").val(b.code)})}}
function bindShowHideYs(a){setAddSubIds("addSubImg","addSubContext");$("#[id^='"+a+"']").bind("click",function(){var a=$(this)[0].id,c="addSubContext"+fiYw(a);if(!isKjExsitIfNotDoAlert(a))return!1;divShowAndHideByJjh(a,c,"/images/ht/common/ht_s_006.svg","/images/ht/common/ht_s_011.svg")})}
function bindKindEditor(a,b,c,d){d=d?d:null;var e="",f="";switch(c?1*c:3){case 3:e=getActionByHz("adminUploadAction!uploadByKeAjax.action?lyProJc="+b),f=getActionByHz("adminFileMaAction!fileMaByKeAjax.action?lyProJc="+b)}KindEditor.ready(function(b){b.create("textarea[id='"+a+"']",{id:a,uploadJson:e,fileManagerJson:f,allowFileManager:!0,afterCreate:function(){},afterChange:function(a){this.sync();d&&textLimitKindEditor(this,this.id+"LimitShow",d)}})})}
function bindPopDiv(a){bindPopDivWithTitle(a,"\u6d88\u606f")}function bindPopDivWithTitle(a,b){$("#"+a).bind("click",function(){$("#popDiv_"+a).dialog({title:b,modal:!0,width:"auto",height:"auto",draggable:!0,resizable:!1,dragStop:function(a,b){$(this).parent(".ui-draggable").width("auto");$(this).parent(".ui-draggable").height("auto")}})})}
function bindPopDivWithTitleAndCallBack(a,b){$("#"+a).bind("click",function(){$("#popDiv_"+a).dialog({title:b,modal:!0,width:"auto",height:"auto",draggable:!0,resizable:!1,buttons:{"\u786e\u5b9a":function(){$(this).dialog("close");callbackPopDivQd(a)},"\u53d6\u6d88":function(){$(this).dialog("close");callbackPopDivQx(a)}},dragStop:function(a,b){$(this).parent(".ui-draggable").width("auto");$(this).parent(".ui-draggable").height("auto")}})})}
function bindTreeViewByLoadedData(a,b){$("#treeViewUL_"+b).treeview();$("#treeViewUL_"+b+" span").bind("click",function(){$("#popDiv_"+b).dialog("close");$("#"+a).val($(this)[0].id);$("#"+b).val($(this).text())})}function bindTreeViewContextMenu(){$("ul[id^='treeViewUL'] li").each(function(){$(this).contextMenu("rightClickDiv",{bindings:{add:function(a){return pauseJsGn()},edit:function(a){return pauseJsGn()},"delete":function(a){return pauseJsGn()}}})})}
function bindAjax(a,b,c){$("#"+a).bind("click",function(){$.post(b,{jsonData:c},function(a){alertMessageBox(a.message)})})}function bindAjaxWithConfirm(a,b,c,d){$("#"+a).bind("click",function(){confirm(d)&&$.post(b,{jsonData:c},function(a){alertMessageBox(a.message)})})}function bindZdButton(a){$("#"+a).bind("click",function(){$("#[id^='addSubContext']").each(function(){var a=$(this).attr("id");$(this).is(":hidden")||(a=a.substring(13,a.length),$(this).show(),$("#addSubImg"+a).click())})})}
function bindZkButton(a){$("#"+a).bind("click",function(){$("#[id^='addSubContext']").each(function(){var a=$(this).attr("id");$(this).is(":hidden")&&(a=a.substring(13,a.length),$(this).hide(),$("#addSubImg"+a).click())})})}function bindCustomInput(a){$(a).customInput()}function bindJqueryTimetabs(a){$(a).addClass("enabled").timetabs({defaultIndex:0,interval:5E3,continueOnMouseLeave:!0,animated:"fade",animationSpeed:1E3})}
function bindShowSpanBySelect(a){$("#"+a).bind("change",function(){var b=$(this).val();$("#"+a+"Span").text(b)})}function bindSubmitExcelPltj(a,b,c){$("#"+a).bind("click",function(){var a=$.trim($("#fileExcel").val());-1!=a.indexOf(".")?(a=a.substring(a.lastIndexOf(".")+1,a.length),"xls"!=a||"xlsx"!=a?alertMessageBox("\u8bf7\u4e0a\u4f20Excel\u6587\u4ef6!"):startSubmitBySetAction(b,c)):alertMessageBox("\u8bf7\u4e0a\u4f20Excel\u6587\u4ef6!")})}
function bindJueryMultiselect(a,b){$("#"+a).multiselect({multiple:!1,selectedList:1,noneSelectedText:b,open:function(a,b){}})}function bindJueryMultiselect002(a,b,c){$("#"+a).multiselect({multiple:!1,maxWidth:b,selectedList:1,noneSelectedText:c,open:function(a,b){}})}function bindSubmit(a,b){$("#"+a).bind("click",function(){checkParam()&&startSubmit(b)})}function bindSubmitAndSetAction(a,b,c){$("#"+a).bind("click",function(){checkParam()&&startSubmitBySetAction(b,c)})}
function bindSubmitAndSetActionAndCheckConfirm(a,b,c,d){$("#"+a).bind("click",function(){checkParam()&&confirm(d)&&startSubmitBySetAction(b,c)})}function bindSubmitAndSetActionAndCheckAndSetBeforeValue(a,b,c){$("#"+a).bind("click",function(){checkParam()&&(setBeforeSubmitValue(),startSubmitBySetAction(b,c))})}function bindSubmitNoCheckParam(a,b){$("#"+a).bind("click",function(){startSubmit(b)})}
function bindSubmitNoCheckParamAndSetAction(a,b,c){$("#"+a).bind("click",function(){startSubmitBySetAction(b,c)})}function bindSubmitNoCheckParamAndSetActionAndCheckConfirm(a,b,c,d){$("#"+a).bind("click",function(){confirm(d)&&startSubmitBySetAction(b,c)})}function bindSubmitNoCheckParamAndSetActionAndSetBeforeValue(a,b,c){$("#"+a).bind("click",function(){setBeforeSubmitValue();startSubmitBySetAction(b,c)})}
function bindSubmitByCuByMuti(a,b){$("#"+a).bind("click",function(){checkParam()&&bindSubmitByMutiEx(b)})}function bindSubmitByInByMuti(a,b){$("#"+a).bind("click",function(){checkParam()&&(addOneByPageLevel(),bindSubmitByMutiEx(b))})}function bindSubmitByBcByMuti(a,b){$("#"+a).bind("click",function(){checkParam()&&(subOneByPageLevel(),bindSubmitByMutiEx(b))})}function bindSubmitAndSetActionByCuByMuti(a,b,c){$("#"+a).bind("click",function(){checkParam()&&bindSubmitBySetActionByMutiEx(b,c)})}
function bindSubmitAndSetActionByInByMuti(a,b,c){$("#"+a).bind("click",function(){checkParam()&&(addOneByPageLevel(),bindSubmitBySetActionByMutiEx(b,c))})}function bindSubmitAndSetActionByBcByMuti(a,b,c){$("#"+a).bind("click",function(){checkParam()&&(subOneByPageLevel(),bindSubmitBySetActionByMutiEx(b,c))})}function bindSubmitAndSetActionAndCheckConfirmByCuByMuti(a,b,c,d){$("#"+a).bind("click",function(){checkParam()&&confirm(d)&&bindSubmitBySetActionByMutiEx(b,c)})}
function bindSubmitAndSetActionAndCheckConfirmByInByMuti(a,b,c,d){$("#"+a).bind("click",function(){checkParam()&&confirm(d)&&(addOneByPageLevel(),bindSubmitBySetActionByMutiEx(b,c))})}function bindSubmitAndSetActionAndCheckConfirmByBcByMuti(a,b,c,d){$("#"+a).bind("click",function(){checkParam()&&confirm(d)&&(subOneByPageLevel(),bindSubmitBySetActionByMutiEx(b,c))})}
function bindSubmitAndSetActionAndCheckAndSetBeforeValueByCuByMuti(a,b,c){$("#"+a).bind("click",function(){checkParam()&&(setBeforeSubmitValue(),bindSubmitBySetActionByMutiEx(b,c))})}function bindSubmitAndSetActionAndCheckAndSetBeforeValueByInByMuti(a,b,c){$("#"+a).bind("click",function(){checkParam()&&(setBeforeSubmitValue(),addOneByPageLevel(),bindSubmitBySetActionByMutiEx(b,c))})}
function bindSubmitAndSetActionAndCheckAndSetBeforeValueByBcByMuti(a,b,c){$("#"+a).bind("click",function(){checkParam()&&(setBeforeSubmitValue(),subOneByPageLevel(),bindSubmitBySetActionByMutiEx(b,c))})}function bindSubmitNoCheckParamByCuByMuti(a,b){$("#"+a).bind("click",function(){bindSubmitByMutiEx(b)})}function bindSubmitNoCheckParamByInByMuti(a,b){$("#"+a).bind("click",function(){addOneByPageLevel();bindSubmitByMutiEx(b)})}
function bindSubmitNoCheckParamByBcByMuti(a,b){$("#"+a).bind("click",function(){subOneByPageLevel();bindSubmitByMutiEx(b)})}function bindSubmitNoCheckParamAndSetActionByCuByMuti(a,b,c){$("#"+a).bind("click",function(){bindSubmitBySetActionByMutiEx(b,c)})}function bindSubmitNoCheckParamAndSetActionByInByMuti(a,b,c){$("#"+a).bind("click",function(){addOneByPageLevel();bindSubmitBySetActionByMutiEx(b,c)})}
function bindSubmitNoCheckParamAndSetActionByBcByMuti(a,b,c){$("#"+a).bind("click",function(){subOneByPageLevel();bindSubmitBySetActionByMutiEx(b,c)})}function bindSubmitNoCheckParamAndSetActionAndCheckConfirmByCuByMuti(a,b,c,d){$("#"+a).bind("click",function(){confirm(d)&&bindSubmitBySetActionByMutiEx(b,c)})}function bindSubmitNoCheckParamAndSetActionAndCheckConfirmByInByMuti(a,b,c,d){$("#"+a).bind("click",function(){confirm(d)&&(addOneByPageLevel(),bindSubmitBySetActionByMutiEx(b,c))})}
function bindSubmitNoCheckParamAndSetActionAndCheckConfirmByBcByMuti(a,b,c,d){$("#"+a).bind("click",function(){confirm(d)&&(subOneByPageLevel(),bindSubmitBySetActionByMutiEx(b,c))})}function bindSubmitNoCheckParamAndSetActionAndSetBeforeValueByCuByMuti(a,b,c){$("#"+a).bind("click",function(){setBeforeSubmitValue();bindSubmitBySetActionByMutiEx(b,c)})}
function bindSubmitNoCheckParamAndSetActionAndSetBeforeValueByInByMuti(a,b,c){$("#"+a).bind("click",function(){setBeforeSubmitValue();addOneByPageLevel();bindSubmitBySetActionByMutiEx(b,c)})}function bindSubmitNoCheckParamAndSetActionAndSetBeforeValueByBcByMuti(a,b,c){$("#"+a).bind("click",function(){setBeforeSubmitValue();subOneByPageLevel();bindSubmitBySetActionByMutiEx(b,c)})}function bindSubmitByMutiEx(a){isKjExsitIfNotDoAlert("submitType")&&startSubmit(a)}
function bindSubmitBySetActionByMutiEx(a,b){isKjExsitIfNotDoAlert("submitType")&&startSubmitBySetAction(a,b)}function bindSubmitSearch(a,b){$("#"+a).bind("click",function(){checkParamBySearch()&&bindSubmitSearchEx()&&startSubmit(b)})}function bindSubmitSearchAndSetAction(a,b,c){$("#"+a).bind("click",function(){checkParamBySearch()&&bindSubmitSearchEx()&&startSubmitBySetAction(b,c)})}
function bindSubmitSearchAndSetActionAndSetBeforeSubmitValue(a,b,c){$("#"+a).bind("click",function(){checkParamBySearch()&&bindSubmitSearchEx()&&(setBeforeSubmitValueBySearch(),startSubmitBySetAction(b,c))})}function bindSubmitSearchEx(){return isKjExsitIfNotDoAlert("submitType")?($("#submitType").val("\u70b9\u51fb\u641c\u7d22"),!0):!1};
